### ISSUE TITLE
(bug or feature lacked?) Reload CURRENT file ONLY, by menu command or automatically when the current editor file changed

### ISSUE THREAD

**Issue by dr-dba** [EugeneManushkin/Yalta#1]
Reload CURRENT file only by menu command, or automatically when the current editor file changed ?

Hello, i am trying to make use of it, looks good.
I also use Yalta, as i am working with Lua files, looks very good.
I am stumbled with some real life case scenario, and it looks like rather important for smooth using in development tasks.
see as the title says.
Lets consider this scenario (using FAR editor of course) :

1.) Programmer created new Lua file, or added some new functions in the opened file
2.) Programmer wants to be able to navigate to the functions
3.) .. and it can not, because the repository is not updated
4.) Programmer can not to reindex the entire repository each time he makes a change
5.) .. because it is too many mess to do, also from the convenice standpoint, and also from the performance overhead

Would not it be great, to detect file changes, and update correspondedly only the current file tags, kind of on the fly?

Thank you!

**Comment by dr-dba** [comment]
(I should better place the issue under the CtagsSourceNavigator FAR plugin)
I put it here:
https://github.com/EugeneManushkin/CtagsSourceNavigator/issues/79#issue-1144810242

**Comment by EugeneManushkin** [comment]
Fixed in https://github.com/EugeneManushkin/CtagsSourceNavigator/issues/79
